# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraine" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_amd64.tar.gz"
      sha256 "d4a9517d0921d39d1330be4bbf80bc563a3f6aa351e0d07171bcc49ffeda460c"
    end
    on_arm do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_arm64.tar.gz"
      sha256 "f3ff68cab62c4019d7df2476da4c482bd05cca0519cea3f0319615802f1df249"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_linux_amd64.tar.gz"
      sha256 "2a5c83375492930a4f4a11c4e9329a8b9fc236b833114718e339d3cef8676259"
    end
  end

  name "migraine"
  desc "Database migration tool for PostgreSQL with change-set management and SQL linting"
  homepage "https://github.com/thegorangers/migraine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraine"

  # No zap stanza required

end
