# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraine" do
  name "migraine"
  desc "Database migration tool for PostgreSQL with change-set management and SQL linting"
  homepage "https://github.com/thegorangers/migraine"
  version "0.0.1-beta.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraine"

  on_macos do
    on_intel do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_amd64.tar.gz"
      sha256 "87de15795170e3a3ac01bca6b7dc86dc27e8d09cbf4d5dcc0eea146e522f6433"
    end
    on_arm do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_arm64.tar.gz"
      sha256 "663791b030304002a5c0ff11baf2573de384947e7bee66bab99a5cb2db6348a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_linux_amd64.tar.gz"
      sha256 "7078fc34573f8755a015f9006300e9237d339796ad990fdcfa9bbb1c64a65068"
    end
  end

  # No zap stanza required
end
