# This file was generated by GoReleaser. DO NOT EDIT.
cask "migraine" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "4354a2245b045b0f0d18a80badf86c5045631dd59e71d467e9fac7b868a7bf31"
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "708b9a726a354db9804eef4e893112d7e3d0a3863e6c6303c2a1060cd3d4ebdc"
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "98f92574d2c560be041f5c6a135a50d9de7e0284d136858e21957a0113bf53d2"
      url "https://github.com/thegorangers/migraine/releases/download/v#{version}/migraine_#{version}_linux_amd64.tar.gz"
    end
  end

  name "migraine"
  desc "Database migration tool for PostgreSQL with change-set management and SQL linting"
  homepage "https://github.com/thegorangers/migraine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migraine"

  # No zap stanza required
end
